### ISSUE TITLE
 Implicitly marking parameter $.... as nullable is deprecated

### ISSUE THREAD

**Issue by antoniovj1** [reactphp/reactphp#593] opened 2024-12-11 08:28 UTC
Since the PHP 8.4 version I'm getting a few errors like this one:

`React\Promise\Promise::resolver(): Implicitly marking parameter $onFulfilled as nullable is deprecated
`

I think is not hard to fix, is help needed?

Thanks

**Comment by clue** [comment] 2024-12-11 08:35
We have you covered already from day one, it looks like you're using an outdated version, please update to the latest version first.

Closing as duplicate of https://github.com/orgs/reactphp/discussions/589 and https://github.com/reactphp/promise/pull/260.

I hope this helps! :+1: If so, consider supporting this project, for example by [becoming a sponsor](https://github.com/sponsors/reactphp) ❤️

**Closed as not planned by clue** 2024-12-11 08:35 UTC
Labels: invalid
